### ISSUE TITLE
Minor: Odd button background when clicking 'Save Answer', or 'Save' for test attempt

### ISSUE THREAD

**Issue by jthambly** [timklapdor/learning-materials#101]
When clicking the save button for a test attempt, a flash of a multi-image background will occur for the background of the button. It should be noted that this is still an improvement compared to the initial theme version.

[Test_Attempt.zip](https://github.com/timklapdor/learning-materials/files/1750575/Test_Attempt.zip)

**Comment by timklapdor** [comment]
Looks like there might be an active state with a different background setting.
