### ISSUE TITLE
Grade Centre - Padding and Font Colour

### ISSUE THREAD

**Issue by jthambly** [timklapdor/learning-materials#106]
Some Grade Centre issues have been a hot topic in user discussions (I thought it would be best to get a listing). Currently, in QA the spreading out of Grade Centre has improved usability, but there are a couple of remaining user concerns that may need to be addressed.

1. Cell Padding, there may be some padding that could be made leaner.
2. Font colour, concerns about the font colour has been raised.
3. Scrolling, this may have since been improved and could perhaps be further improved by padding adjustments.

**Comment by timklapdor** [comment]
Padding and Scrolling 1 & 3 are addressed in #107 

Will open up another issue looking at colour issues - see #116
