### ISSUE TITLE
Less students visible in Grade Centre

### ISSUE THREAD

**Issue by sparkercsu** [timklapdor/learning-materials#107]
Now only shows 10 when 13 were previously present.

As it needs to be a very functional page more students would be better.

![2018-02-23 17_17_43-grade centre s-mgt220_201730_w_d csu](https://user-images.githubusercontent.com/22672442/36580802-e3743396-18bd-11e8-9161-e56cd7dd4e22.png)
![2018-02-23 17_16_28-grade centre s-mgt220_201730_w_d csu](https://user-images.githubusercontent.com/22672442/36580803-e3a31a58-18bd-11e8-99f5-984b4095fe56.png)

**Comment by timklapdor** [comment]
seems to be change in padding between versions - not my changes - but in grading.css. Can change with:

```
.gbtable tbody tr td, .gbtable tbody tr th, .gbtable_header th, .gbtable thead th {
    padding: 3px !important;
}
```

**Comment by timklapdor** [comment]
Added to theme
