### ISSUE TITLE
Achievement options are presenting weirdly

### ISSUE THREAD

**Issue by sparkercsu** [timklapdor/learning-materials#108]
![2018-02-23 16_11_05-create achievement s-mgt220_201630_w_d csu qa](https://user-images.githubusercontent.com/22672442/36580994-ccd23b96-18be-11e8-8901-770fe1e8338f.png)
![2018-02-23 17_26_39-create achievement s-mgt220_201730_w_d csu](https://user-images.githubusercontent.com/22672442/36580995-ccfdaf88-18be-11e8-8ef0-92b7394b3c4b.png)

**Comment by timklapdor** [comment]
OK - yet another menu class and setup in Bb! Have added padding to bring it into the section and a hover for the other options.

```
.mapTabs {
padding-bottom: 2em;
}

.mapTabs a:hover {
    color: $primary;
}
```
