### ISSUE TITLE
oversized manual page-open text

### ISSUE THREAD

**Issue by helsouth** [timklapdor/learning-materials#15]
rather dominates top of screen when reading page. AFAIK tends to be superfluous, never known a page to not open. [Chrome on Win10]
![open](https://user-images.githubusercontent.com/9177588/31530808-9a958b36-b02e-11e7-92ec-e6f319761568.png)

**Comment by timklapdor** [comment]
Could you give me access to the site and a direct link. Not sure how to create this ... cheers

**Comment by helsouth** [comment]
added.

Here's the direct link
https://interact2.csu.edu.au/webapps/blackboard/execute/displayLearningUnit?content_id=_1596926_1&course_id=_26494_1&mode=view

you see this message when in student preview.  It's pretty darn huge in the
existing site, actually - I was sure it wasn't that bad - it used to be
quite small.

It's likely not a huge issue. As small-screen laptop user, I generally
resent anything that uses up screen real estate. I'm probably not your
ideal product tester :)

**Comment by timklapdor** [comment]
added new css to address the issue. will come in next theme update.
