### ISSUE TITLE
Faculty Banner (in subject) is a little blocky

### ISSUE THREAD

**Issue by MorganLuck** [timklapdor/learning-materials#19]
Is this too small of a thing to think about? Feel like I'm scraping the bottom here.

**Comment by timklapdor** [comment]
zoom issue - need to do some work around responsive images in sites.

**Comment by timklapdor** [comment]
Banner image is blurry... will accept any height image... might need to work on solution for this

**Comment by timklapdor** [comment]
Going to close as this is an issue with Bb and the image itself not the theme
