### ISSUE TITLE
Portfolio elements and portrait orientated images

### ISSUE THREAD

**Issue by ryunf** [timklapdor/learning-materials#49]
Issue with 1 up, 2 up etc Portolio elements and how they handle portrait orientated images. 

Portrait images left align in the column but don't fill its width. The background colour and border however do fill the width of the column. It would be good to either be able to fill the width of the column with a portrait image the same as square and landscape images or, be able to remove the background colour and border and centre align the image to the column.

**Comment by timklapdor** [comment]
Have you got an image demonstrating the behaviour?

**Comment by ryunf** [comment]
This image shows both the landscape and portrait behaviour.
![porfolio-image](https://user-images.githubusercontent.com/35583826/35311067-b5df45c8-0108-11e8-9b20-97390834a1f7.jpg)

**Comment by timklapdor** [comment]
In the CSS a width of 100% has been set for the image - so you can leave out the width and height of the image from the ```<img>``` tag. I could only recreate the issue if image dimensions were added to the tag.

**Comment by ryunf** [comment]
Looks like Placeholder.com images act the same as declaring the width inline even though they shrink and expand in the responsive layout. Will pass that on but prob needs adding to the style guide. 

Can we still look at an option to not have the background colour and box-shadow?

**Comment by timklapdor** [comment]
the background and shadow come from the surrounding ```<figure>``` so if you just place the image there without it will work fine. Actually if you take the image out of the ```<figure>``` then you can set width if required. Figure just tries to make everything responsive.

**Comment by ryunf** [comment]
Yeah but was kind of hoping we could keep using `figure` so we can also use `figcaption` and make use of the responsiveness.

**Comment by timklapdor** [comment]
OK - will add a ```.no-style``` for figure which will remove the background and dropshadow.

**Comment by timklapdor** [comment]
Added to update in theme
