### ISSUE TITLE
Faculty icons (64x64px)

### ISSUE THREAD

**Issue by helengorman** [timklapdor/learning-materials#50]
Existing faculty icons (in DOMS) are 64x64px and if embedded in an activity box in the new skin appear blurry. However, if icons are 192x192px they look much better. Also if kept in old table arrangement they are OK yet small.

Q. Would it be a good idea (for me) to re-export a new set of Faculty icons and upload to DOMS so to cater for users who want to use these icons in a new styled activity box? ...and/or
Q. Could there possibly be a quick fix that could be implemented in the CSS/HTML? ...and/or
Q. Is it OK to continue using the old style icon/table arrangement in the new skin?

I have provided example below:
![fac-icons-issue](https://user-images.githubusercontent.com/34092884/35649072-01907a22-072c-11e8-8104-66a9f7e207f2.png)

The project I am currently working on uses below icons which I have re-exported to larger size and uploaded to DOMS:
![new-skin-icon](https://user-images.githubusercontent.com/34092884/35650175-6a15c662-072f-11e8-9842-5468368409d3.png)

Happy to re-export Faculty icon sets (and any other icons I have created) to larger size and upload to DOMS if tweaks in CSS/HTML can't be done.

**Comment by timklapdor** [comment]
Workarounds provided
