### ISSUE TITLE
Browsers

### ISSUE THREAD

**Issue by kxh210** [timklapdor/learning-materials#56]
Hi
Staff and students viewing I2 in IE is 'not good'. We are aware that I2 help does say to use FireFox and Chrome but does not explicitly state why IE should not be used.

Are staff and students aware that they should avoid using IE? 
Some staff use IE as it is usually the default browser on their computers and we have just realised that this may be why we have certain issues coming into the SRS.

Regards

Kerri

**Comment by timklapdor** [comment]
Hi Kerri - There are some issues in support for IE. Microsoft have deprecated the product and it is no longer supported. We are looking at updating the info provided by DIT and student Central to reflect this and to adopt Firefox or Chrome. Edge and Safari were included in testing and don't have the same problems. I'll keep this issue open until DIT resolve it.

**Comment by kxh210** [comment]
Thank you
