### ISSUE TITLE
Table borders

### ISSUE THREAD

**Issue by ryunf** [timklapdor/learning-materials#57]
Tables are having borders removed by the theme package. Can this be amended so standard table attributes remain unaffected and new table styles are added through classes.

**Comment by timklapdor** [comment]
remove this from appnav.css

```
#containerdiv .vtbegenerated td {
  border: 0; 
}
```

**Comment by ryunf** [comment]
Nice.

Ryun Fell
Manager, Media and Technology
Learning Resources | Division of Learning and Teaching
Charles Sturt University
Panorama Avenue
Bathurst, NSW 2795
Australia
Tel: +61 2 6338 4157
Fax: +61 2 6338 4356
Email: rfell@csu.edu.au<mailto:rfell@csu.edu.au>
www.csu.edu.au
