### ISSUE TITLE
Table columns breaking out of right-hand content margin

### ISSUE THREAD

**Issue by ryunf** [timklapdor/learning-materials#58]
Far right columns of tables are breaking out of the content area margin between breakpoints. Happens to be at a common resolutions for staff issued monitors

**Comment by timklapdor** [comment]
Can I get an idea of screen resolution and a screenshot?

**Comment by timklapdor** [comment]
Need to retest with updated theme.

**Comment by timklapdor** [comment]
Content area now has a % width. Further issues may be to do with fixed with of table or items inside.
