### ISSUE TITLE
Support for valid font-size style

### ISSUE THREAD

**Issue by ryunf** [timklapdor/learning-materials#60]
Theme needs to provide support for valid font size styles used extensively in live subject sites. Support is requested for the below valid styles:

style="font-size:xx-small;"
style="font-size:x-small;"
style="font-size:small;"
style="font-size:medium;"
style="font-size:large;"
style="font-size:x-large;"
style="font-size:xx-large;"
style="font-size:smaller;"
style="font-size:larger;"

**Comment by timklapdor** [comment]
Bb has inconsistently applied font sizes - some are names others have a px value. I don't think I can make CSS to distinguish between the two. The testing I did had more use of pixels vs font names. I wonder if this is a carry over from sakai?

If there's a way to ignore font-size named and unset font-size px I would implement it to fix this. Just not sure of our options.

**Comment by ryunf** [comment]
See “CSS Syntax - Property Values” section, these all worked under the old theme but aren’t working now (appear to work in IE ironically): https://www.w3schools.com/cssref/pr_font_font-size.asp


Ryun Fell
Manager, Media and Technology
Learning Resources | Division of Learning and Teaching
Charles Sturt University
Panorama Avenue
Bathurst, NSW 2795
Australia
Tel: +61 2 6338 4157
Fax: +61 2 6338 4356
Email: rfell@csu.edu.au<mailto:rfell@csu.edu.au>
www.csu.edu.au

**Comment by timklapdor** [comment]
The issue isn't the named styles though - its the fonts that are sized with pixels. To address these I have to address all inline font-size settings in the same way and ```unset``` them. Then the theme comes over and resets them at a size consistent with the base element.  I'm not sure if I can get the ```unset``` to ignore named sizes or to only change ones with pixels. 

I'll explore if I can perhaps use the data selector... https://css-tricks.com/almanac/selectors/a/attribute/

**Comment by timklapdor** [comment]
Font names are **user defined** - so set in the browser, not accessible to css so cannot be changed. They are css attributes that operate outside the CSS cascade. With Blackboard we are dealing with a number of problems all at once

- inline styles 
>" inline styles have the highest precedence or specificity in a document. This means they are going to be applied no matter what else is dictated in your external stylesheet"
- named styles are user styles
>"The only styles that have higher precedence than inline styles are user styles applied by the readers themselves."
- Specificity rules in the CSS. If you want to overwrite something outside the cascade you have to be more specific than the value. The spaghetti of code in Bb makes this virtually impossible - riddled with tables for layout and more spans that you can poke a stick at it's almost impossible to be that specific. 

Named styles are not actionable CSS objects so we can't use them. 

https://www.thoughtco.com/what-is-css-inline-style-3466446
