### ISSUE TITLE
Header level comparative sizing

### ISSUE THREAD

**Issue by ryunf** [timklapdor/learning-materials#62]
A number of reports are indicating that there is still an issue with header levels. Some paragraph text is appearing either the same size or even larger than the header text that proceeds it.

**Comment by timklapdor** [comment]
I think this would be a markup issue - that the headings aren't semantically <headings> - just normal paragraphs with inline settings for font-size and weight.

**Comment by ryunf** [comment]
H3 are appearing smaller than H4. H4 is barely bigger than P. Yep, HTML usage is most cases but differentiation between semantic levels is still be reported as a concern.

**Comment by timklapdor** [comment]
Updated heading size: 

h1 {font-size: 200%;
h2 {font-size: 180%;
h3 {font-size: 160%;
h4 {font-size: 140%;
h5 {font-size: 120%;
h6 {font-size: 110%;
p {font-size: 100%;
