### ISSUE TITLE
Indent

### ISSUE THREAD

**Issue by rstewartallan** [timklapdor/learning-materials#64]
The indent button on the editor no longer works. The class="indent" won't work either.

**Comment by timklapdor** [comment]
Thanks Rachel. I think I have diagnosed the problem here. The theme CSS uses margins to apply spacing between paragraphs but this overwrites the left and right margins too. I can put a fix in for that into the theme. 

Will have to check for other fixes to roll into a single update.

**Comment by timklapdor** [comment]
removing !important from margins text elements - p, h1-h6
