### ISSUE TITLE
Global Navigation unable to fully show left menu icons

### ISSUE THREAD

**Issue by jthambly** [timklapdor/learning-materials#72]
A left-hand vertical appearing sidebar has been introduced (or exaggerated) pushing the menu icons to the right.

**Comment by timklapdor** [comment]
Can you add a screenshot? Thx

**Comment by jthambly** [comment]
Yes, sure. 

![global navigation new](https://user-images.githubusercontent.com/33741581/36402544-790cc752-1633-11e8-9d81-3843e735ac12.png)
![global navigation original](https://user-images.githubusercontent.com/33741581/36402545-796e99be-1633-11e8-92ef-90fc541286d9.png)

**Comment by jthambly** [comment]
Screen resolutions:

Repeatable on each of my monitors.

1680 x 1050 (1 x monitor)
1920 x 1080 (2 x monitors)

**Comment by timklapdor** [comment]
OK - found an errant UL css tag that was affecting this. Will remove in the update!

**Comment by timklapdor** [comment]
An unattributed (not linked to an element or page area) element was causing this. Have remove the following from styles: 

ul {
    padding-left: 2em !important; 
}
