### ISSUE TITLE
Browser freezing

### ISSUE THREAD

**Issue by mlangham01** [timklapdor/learning-materials#73]
ACC515 (WD) - Academic was trying to add a video link to his landing page and it kept freezing on him.  He was using IE.  I tried to add the link to the landing page in FireFox and it froze on me.  I then tried Chrome and typing was so slow.  DLT requests is 12402, he has also logged a job with DIT20811.

**Comment by timklapdor** [comment]
Hi Michelle, 

This sounds like a system/browser issue. I'd recommend that the academic updates to a more modern browser - it should improve their experience in general. The stalling and freezing - definitely system related - so logging the job was the right way to go. I'll keep this open for the time being .... if you can update it with the outcome of the DIT job that would be great. Would like to eliminate this from my list.

**Comment by mlangham01** [comment]
Hi Tim, finally got to the bottom of this job.  DIT has found that probably the academic had copied and pasted his landing page, which transferred over enormous html code that wasn't required.  This was making the browser freeze.  The DIT job was assigned to David Roma.

**Comment by timklapdor** [comment]
Cool - I'll close this as it's not a problem with the theme :-)
