### ISSUE TITLE
Grade Centre Weird Background

### ISSUE THREAD

**Issue by timklapdor** [timklapdor/learning-materials#74]
When you hover over 'Layout Position' or 'Ascending' you get little green ticks on the first option (see screen shot).

![image](https://user-images.githubusercontent.com/4554100/36403679-8d026b48-163a-11e8-94e4-559ac7184f66.png)

**Comment by timklapdor** [comment]
Adding you to the issues so you can track progress @mlangham01

**Comment by timklapdor** [comment]
Background positioning seems to be getting over ridden. Add this to appnav

```
ul.selectList li.sub ul li.current a, ul.selectList li.sub ul li.current a:hover, .nav .sub .current a, .nav .sub .current a:hover, .nav .sub .current.favorite a, .nav .sub .current.favorite a:hover {
background-repeat: no-repeat !important;
background-position: 2px  center !important;
}
```

**Comment by jthambly** [comment]
Fixed, but green tick touching text.
![image](https://user-images.githubusercontent.com/33741581/36460678-9509caba-170d-11e8-8f95-335b2d4fe5a0.png)
