### ISSUE TITLE
QA version: Announcement text overlap in edit mode

### ISSUE THREAD

**Issue by ryunf** [timklapdor/learning-materials#78]
Text/ columns overlap in the Annoucement Tool when in editor mode (also renders editing impossible as chevron is hidden).

Prod screen grab:
![announcement-prod](https://user-images.githubusercontent.com/35583826/36464237-ce3e3be4-1722-11e8-9184-4485f10e9764.jpeg)

QA screen grab:
![announcement-qa](https://user-images.githubusercontent.com/35583826/36464245-da87b13c-1722-11e8-8c47-bdef2dd679d4.jpeg)

**Comment by timklapdor** [comment]
Added media query and increased padding to announcement info

```
@media screen and (max-width: 800px) {

  .announcementList h3.item {
    padding: 3em 0 2em 0 !important;
  }

  div.announcementInfo {
    width: 90%;
    border: none;
  }

  .announcementList .details, #announcementList .details {
    margin: 0;
  }
}
```
