### ISSUE TITLE
QA Version: Grade Centre Column Titles Not Visible

### ISSUE THREAD

**Issue by mpdeans** [timklapdor/learning-materials#79]
> My Grades

Titles - 'Item', 'Last Activity' and 'Grade' are not shown.

Old
![titles1](https://user-images.githubusercontent.com/36716537/36511937-d6fe22fe-17bc-11e8-9431-94806789d916.png)

New
![titles2](https://user-images.githubusercontent.com/36716537/36511947-e5e0a558-17bc-11e8-9d03-1ae5f9e38b49.png)

**Comment by timklapdor** [comment]
seems to be issue with top value - placing it underneath the header. Changing to :

```
.gradeTableNew .grades_header {
top: unset;
}
```
seems to fix
