### ISSUE TITLE
QA Version: Menu Highlights Hide Content

### ISSUE THREAD

**Issue by mpdeans** [timklapdor/learning-materials#81]
When clicking on the top bar menu items (for tools which use it), the first item is highlighted - normal behaviour - but in the new skin the highlight blocks out the text - or more accurately it seems to change the text to white as well as highlight white. On hover works normally.

Old
![group1](https://user-images.githubusercontent.com/36716537/36513282-0cbb024e-17c3-11e8-9cb4-d67350a429d8.png)

New Examples
![group2](https://user-images.githubusercontent.com/36716537/36513305-28b6f0f2-17c3-11e8-9d15-09da062ec188.png)
![group3](https://user-images.githubusercontent.com/36716537/36513314-31f05e7e-17c3-11e8-9dd6-02311d820ff8.png)

**Comment by timklapdor** [comment]
Which browser? Trying to recreate it.

**Comment by timklapdor** [comment]
I get this... 
<img width="470" alt="screen shot 2018-02-22 at 12 41 35" src="https://user-images.githubusercontent.com/4554100/36515488-c2e33b72-17cd-11e8-87fd-261970d3ca0c.png">

**Comment by timklapdor** [comment]
Ok - javascript seem to change the state to ```focus``` when clicked - no click no problems. Have found a fix:

```
#bcMenu ul li a:focus {
color: red !important;  
}
```

Seems to work.

**Comment by mpdeans** [comment]
This fix doesn't appear to have been applied across the boards. It works for 'Content' areas (i.e. Build Content) but not for others. e.g. Groups, Content Collection.
![contentcoll](https://user-images.githubusercontent.com/36716537/36575858-548cff44-18a1-11e8-81d1-11dd1acad0e0.png)

**Comment by timklapdor** [comment]
Might be a seperate ID being applied. Will go in and explore more.

**Comment by timklapdor** [comment]
looks like setting the background as transparent is a fix. Added ```.actionBar ul li a:focus``` to above and tweaked code:
```
#bcMenu ul li a:focus, .actionBar ul li a:focus {
  color: #B00C1D !important;
  background: transparent !important; }
```

**Comment by timklapdor** [comment]
fixed in QA
