### ISSUE TITLE
Drag 'n Drop - Excessive space

### ISSUE THREAD

**Issue by jthambly** [timklapdor/learning-materials#82]
Tested in versions <= 1.1.

The Drag and Drop attachment areas have significantly increased from the original theme.
This space may be regarded as excessive padding by users.

![drag-n-drop-old](https://user-images.githubusercontent.com/33741581/36513706-0618778a-17c5-11e8-8aa0-4b28cfbe32f8.png)
![drag-n-drop-new](https://user-images.githubusercontent.com/33741581/36513708-0687f04c-17c5-11e8-9a96-c6d4ca8e0f2e.png)

**Comment by timklapdor** [comment]
Yep - had a percentage of screen width giving it the padding value. Changed to a font size relative one: ```padding: 3em !important;```
