### ISSUE TITLE
QA Version: Checkbox and Radio Button Alignment

### ISSUE THREAD

**Issue by mpdeans** [timklapdor/learning-materials#83]
Across everything, the new formatting shifts the alignment of checkboxes and radio buttons down. As such they're no longer exactly aligned with their respective text. Even on the old skin this is there, but the line spacing is so small it doesn't make a difference and it aligns mostly as it should.

For many forms this is trivial, but for some it is visually a little confusing as to what you're selecting.

Example showing miss-alignment
![alignment1](https://user-images.githubusercontent.com/36716537/36513796-7ff7dbfe-17c5-11e8-8bf5-bac9628d23c1.png)

Example of where it can be a bit visually confusing for a user
![alignment2](https://user-images.githubusercontent.com/36716537/36513819-a28e7902-17c5-11e8-8670-b16bc6ca8eab.png)

**Comment by timklapdor** [comment]
There was padding on checkbox - have removed:

```
#dataCollectionContainer input[type="checkbox"]{margin-top: .85em !important;}
```

testing now

**Comment by timklapdor** [comment]
Fix in Devel at the moment - seems to resolve most issues. Did set margins at the eelement level instead.

**Comment by mpdeans** [comment]
Looks okay in QA so far.

**Comment by timklapdor** [comment]
👍
