### ISSUE TITLE
QA Version: Font size for links not unset in QA

### ISSUE THREAD

**Issue by mcochran** [timklapdor/learning-materials#84]
Here is a screenshot from current prod:
![interact2](https://user-images.githubusercontent.com/965604/36517486-541713f4-17d6-11e8-8142-0d24805c81b9.PNG)

Here what it looks like in QA:
![interact2qa](https://user-images.githubusercontent.com/965604/36517492-5f29bc60-17d6-11e8-8797-9a4081ac3551.PNG)

**Comment by mcochran** [comment]
MGT320 201730 B D

**Comment by timklapdor** [comment]
Thanks Mark - found ```<em>``` wasn't either
