### ISSUE TITLE
CSU Brand Colours not part of colour scheme

### ISSUE THREAD

**Issue by timklapdor** [timklapdor/learning-materials#9]
need to add csu official brand colours to colour palettes!

**Comment by helsouth** [comment]
suggest these should be minimal: when you spend half your life on a site, you don't need its branding to be in-your-face. Red really leaps off the page. [Also: many students still print]

**Comment by timklapdor** [comment]
Just added these as classes to the theme - so can be called on in designs but aren't called on specifically.

**Comment by helsouth** [comment]
nice solution.
