### ISSUE TITLE
QA version: Print View - Grey vertical bar down page

### ISSUE THREAD

**Issue by jthambly** [timklapdor/learning-materials#92]
QA Test site: O-MGT220_201730_W_D -> Topics -> Topics.
(Tested under Chrome.)
(Edit mode on, to allow full learning modules view).

Grey line down the middle of the page, which occurs for 76 of 141 pages.

![image](https://user-images.githubusercontent.com/33741581/36572607-e0495656-1890-11e8-9442-51b432ad7cdd.png)

**Comment by jthambly** [comment]
may need to find another example.

**Comment by timklapdor** [comment]
Thanks - hadn't tested in edit mode.

**Comment by timklapdor** [comment]
Hi Jason  - In the developer mode can you select the grey line? Just trying to work out which element/id/class it is.

**Comment by jthambly** [comment]
interestingly enough, I am not seeing this bar anymore under the print preview.

**Comment by timklapdor** [comment]
Might be part of the hover which seemed to add stuff when hitting print

**Comment by timklapdor** [comment]
Have cleaned up the print css - so will be going into an update ASAP
