### ISSUE TITLE
QA Version: Dialogue box getting cut off

### ISSUE THREAD

**Issue by ryunf** [timklapdor/learning-materials#93]
When creating a new content area in the left-hand nav, the pop-up dialogue box is cut off on the right.

Prod version:
![content-area-prod](https://user-images.githubusercontent.com/35583826/36573109-625fa8aa-1893-11e8-83c5-8c8ef7f4745d.jpeg)

QA version:
![content-area-qa](https://user-images.githubusercontent.com/35583826/36573123-6bf200de-1893-11e8-94eb-97a4a59d661d.jpeg)

**Comment by timklapdor** [comment]
Removed a general padding that was being applied to lists and causing other issues. Added
```
.quickAddPal ol {
  padding: 1em;
}
```
