### ISSUE TITLE
QA Version: Discussion board descriptor text

### ISSUE THREAD

**Issue by ryunf** [timklapdor/learning-materials#94]
The change in width to the descroption column is noticably improved in the QA version however now the descriptor text is rendering too small (14px).

Prod Version:
![discussion-board-prod](https://user-images.githubusercontent.com/35583826/36573180-b2cc9410-1893-11e8-8b0b-1f84c334e981.jpeg)

QA Version:
![discussion-board-qa-14px](https://user-images.githubusercontent.com/35583826/36573187-bca91a26-1893-11e8-967e-3f060e046d02.jpeg)

**Comment by timklapdor** [comment]
Will adjust that to be 90% of base font... lots of really long descriptions. 

PS is there an extra space on the Discussion Export in the image above.... seems to be spread on two lines and radio looks weird... :-)

**Comment by ryunf** [comment]
Just had a look, actually no. The second line appears to be the chevron the edit. For some reason it is wrapping and not sitting beside the title.

--



On Fri, Feb 23, 2018 at 1:38 PM +1100, "Tim Klapdor" <notifications@github.com<mailto:notifications@github.com>> wrote:


Will adjust that to be 90% of base font... lots of really long descriptions.

PS is there an extra space on the Discussion Export in the image above.... seems to be spread on two lines and radio looks weird... :-)

-

**Comment by timklapdor** [comment]
Resolved in latest update to QA
