### ISSUE TITLE
QA Version: Maths editor hidden in quizzes

### ISSUE THREAD

**Issue by ryunf** [timklapdor/learning-materials#95]
This is in both the Production version and the QA version. The maths editor toolbar is not showing and has a style of `display:none;`. This was not present in the old theme. As a result, formulas can't be entered as an answer for test questions.

Old Theme:
![maths-toolbar-old-theme](https://user-images.githubusercontent.com/35583826/36573558-b73616f0-1895-11e8-937c-16bb33e8bd8b.jpeg)

New Theme (Prod and QA):
![maths-toolbar-prod-qa](https://user-images.githubusercontent.com/35583826/36573563-c29a9246-1895-11e8-813b-7fbc07568a83.jpeg)

Toolbar code screenshot:
![toolbar-qa](https://user-images.githubusercontent.com/35583826/36573578-cd000806-1895-11e8-9b9c-bb89f7e1cbba.jpeg)

The input field is also not filling the container `div class="field"` space and expanding even when the toolbar is forced to unhide.

**Comment by timklapdor** [comment]
It seems to be set to ```display: none;``` inline... it's not inheriting it from the CSS at all!

@jthambly do you know if this is a known issue? I might be able to "fix" it with the theme.

**Comment by timklapdor** [comment]
Looks like I could have a go at fixing it with 
```
div.wrs_toolbar {
display: block !important;
}
```

**Comment by timklapdor** [comment]
Will include in update

**Comment by timklapdor** [comment]
Added my fix to current version
