### ISSUE TITLE
QA Version: "Browser My Computer" button cut off

### ISSUE THREAD

**Issue by ryunf** [timklapdor/learning-materials#97]
When using "Import Package/View Logs" the "Browser My Computer" button beside "Select a Package" is cut off.

**Comment by timklapdor** [comment]
Bb are doing some messed up stuff with overlaid input.... no idea why. 

Changing the overflow seems to remedy

```
.fileInputWrapper {
  overflow: visible;
}
```

**Comment by timklapdor** [comment]
fixed in QA
