### ISSUE TITLE
QA Version: Discussion Forum Column width

### ISSUE THREAD

**Issue by ryunf** [timklapdor/learning-materials#99]
Latest QA version has reverted to a narrow width of the description column in the Discussion tool. The previous QA version had a wider width.

**Comment by timklapdor** [comment]
Are you in firefox? Seems to be different than in Chrome... #100

**Comment by ryunf** [comment]
Ok see what you mean. The font is bigger in Firefox too. Flagging that ESCs will be using Firefox and advising anyone working in MSI to do so also.

**Comment by timklapdor** [comment]
Font size seems to be a scaling difference. Chrome is rounding off. Firefox is doing it do decimal places - so difference based on what screen size.

**Comment by bdalgarno** [comment]
This problem has been reported on Yammer too.

**Comment by timklapdor** [comment]
Same as #100 - progress in there
